---
version: 2

models:
  - name: "big_query_ai_test_cg_1__customers_filtered"
    tags:
      - "prophecy_temp"
  - name: "big_query_ai_test_cg_1__customer_orders"
    tags:
      - "prophecy_temp"
  - name: "big_query_ai_test_cg_1__orders_with_region"
    tags:
      - "prophecy_temp"
  - name: "big_query_ai_test_cg_1__sales_by_region"
    tags:
      - "prophecy_temp"
  - name: "big_query_ai_test_cg_1__top_regions"
    tags:
      - "prophecy_temp"
  - name: "big_query_ai_test_cg_1__final_report"
    tags:
      - "prophecy_temp"
